version: "3.4"
x-logging:
  &default-logging
  options:
    max-size: '10m'
    max-file: '5'
  driver: json-file

services:
  nodeexporter:
    image: prom/node-exporter
    container_name: nodeexporter
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    ports:
      - 9100:9100

  prometheus:
    image: prom/prometheus:${PROMETHEUS_TAG}
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command: >
      --config.file=/etc/prometheus/prometheus.yml
      --storage.tsdb.path=/prometheus
      --storage.tsdb.retention=30d
  #      --web.enable-admin-api
    restart: unless-stopped
    logging: *default-logging


  grafana:
    image: grafana/grafana:${GRAFANA_TAG}
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    volumes:
#      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - grafana_data:/var/lib/grafana
      - ./grafana_db:/var/lib/grafana
    restart: unless-stopped
    logging: *default-logging
    
volumes:
  prometheus_data:
  grafana_data:
