apiVersion: v1
kind: Service
metadata:
  name: hello-python-service
spec:
  selector:
    app: hello-python
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-phone-book
spec:
  selector:
    matchLabels:
      app: final-phone-book
  replicas: 3
  template:
    metadata:
      labels:
        app: final-phone-book
    spec:
      containers:
      - name: final-phone-book
        image: hello-python:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000