apiVersion: 1

# datasources:
#   - name: elasticsearch-v7-filebeat
#     type: elasticsearch
#     access: proxy
#     database: "[filebeat-]YYYY.MM.DD"
#     url: http://localhost:9200
#     jsonData:
#       interval: Daily
#       timeField: "@timestamp"
#       esVersion: 70
#       logMessageField: message
#       logLevelField: fields.level




datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090